title: Path to Spectral
description: Research, AI, and Mathematics
url: "https://pathtoscience.github.io"
baseurl: ""
theme: null

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

navigation:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/
